import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fuji Internation Education Consultancy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
    <html lang="en">
      <link rel="icon" href="/img/favicon.ico" sizes="any" />
      <body className={inter.className}>
       
        {children}
        </body>
    </html>
  );
}
